FROM verificarlo/fuzzy:v0.4.1-lapack-python3.8.5-numpy-scipy

ENV VFC_BACKENDS='libinterflop_ieee.so'

RUN cd /opt/build/ &&\
    git clone https://github.com/yeatmanlab/pyAFQ.git &&\
    cd /opt/build/pyAFQ &&\
    git checkout 0.6 &&\
    sed -i 's/numpy==1.18.5/numpy>=1.18.5,<1.20/g' setup.cfg &&\
    sed -i 's/cvxpy==1.1.5/cvxpy>=1.1.10/g' setup.cfg &&\
    pip3 install .

COPY afq.py /opt/build/afq.py 

RUN cd /opt/build/ &&\
    git clone https://github.com/yohanchatelain/pytracer &&\
    cd /opt/build/pytracer &&\
    pip3 install .

ENV VFC_BACKENDS='libinterflop_mca.so -m rr'
ENV VFC_BACKENDS_LOGGER="True"

